sudo: required

services:
    - docker

before_install:
    - docker build -t kishorekoma/dev1 .

script:
    - docker run kishorekoma/nodejsdoc  npm ls      

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push kishorekoma/dev1
