sudo: required

services:
    - docker

before_install:
    - docker build -t kishorekoma/dev1 .

script:
    - docker run kishorekoma/nodejsdoc  npm ls      

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push kishorekoma/dev1
deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: devproject
    env: Devproject-env
    bucket_name: elasticbeanstalk-us-east-2-531096691206
    bucket_path: devproject
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_acces_key: $AWS_SECRET_KEY
